apiVersion: v1
kind: Namespace
metadata:
  name: FILLED_IN_BY_CI
  labels:
    sandboxId: FILLED_IN_BY_CI
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: FILLED_IN_BY_CI
  namespace: FILLED_IN_BY_CI
  labels:
    sandboxId: FILLED_IN_BY_CI
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: FILLED_IN_BY_CI
spec:
  releaseName: FILLED_IN_BY_CI
  chart:
    git: https://github.com/biomage-org/iac
    path: charts/nodejs
    ref: FILLED_IN_BY_CI
  values:
    # disable readiness probes as load balancer performs
    # its own health checks/cordoning
    readinessProbe:
      probeType: exec
      command: ["echo", "0"]
    loadBalancerHealthCheck:
      path: "/robots.txt"
      periodSeconds: 30
    livenessProbe:
      probeType: tcpSocket
    service:
      additionalHosts: FILLED_IN_BY_CI
  valuesFrom:
  - configMapKeyRef:
      name: account-config
      namespace: flux
      key: account-config.yaml
    # filled in by CI. do not modify.
