codecov:
  require_ci_to_pass: yes

coverage:
  range: 80..100
  round: down
  precision: 2

  status:
    project:                   # measuring the overall project coverage
      default:                 
        enabled: no           
    patch:                    # measuring the coverage of new changes
      default:
        enabled: no