codecov:
  require_ci_to_pass: yes

coverage:
  range: 60..100
  round: down
  precision: 2

  status:
    project:                   # measuring the overall project coverage
      default:                 
        target: auto
        # don't allow new commits to decrease coverage
        # Temporary to merge pr https://github.com/hms-dbmi-cellenics/ui/pull/723
        threshold: 1%

    patch:                    # measuring the coverage of new changes
      default:
        enabled: no
