# pull official base image
FROM node:13.12.0-alpine

ENV PORT 3000

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Installing dependencies
COPY package.json /usr/src/app/
COPY yarn.lock /usr/src/app/
RUN yarn install

# Copying source files
COPY . /usr/src/app

# Building app
RUN yarn build
EXPOSE 5000

# start app
CMD ["yarn", "run", "start"]