/**
 * Sets plot configs and data.
 */
const COMPONENT_CONFIG = 'componentConfig';
const LOAD_CONFIG = `${COMPONENT_CONFIG}/load`;
const UPDATE_CONFIG = `${COMPONENT_CONFIG}/update`;
const RESET_CONFIG = `${COMPONENT_CONFIG}/reset`;
const SAVE_CONFIG = `${COMPONENT_CONFIG}/save`;
const CONFIGS_REPLACED = `${COMPONENT_CONFIG}/replacements`;
const PLOT_DATA_LOADED = `${COMPONENT_CONFIG}/plotDataLoaded`;
const PLOT_DATA_LOADING = `${COMPONENT_CONFIG}/plotDataLoading`;
const PLOT_DATA_ERROR = `${COMPONENT_CONFIG}/plotDataError`;

const TRAJECTORY_NODES_SELECTION_UPDATED = `${COMPONENT_CONFIG}/trajectoryNodesUpdated`;

export {
  LOAD_CONFIG,
  UPDATE_CONFIG, CONFIGS_REPLACED,
  RESET_CONFIG, SAVE_CONFIG,
  PLOT_DATA_LOADED, PLOT_DATA_LOADING, PLOT_DATA_ERROR,
  TRAJECTORY_NODES_SELECTION_UPDATED,
};
