####################
## BD Rhapsody WTA Analysis Pipeline Version 1.11
## Analysis Date - 01 Jan 90 1990 00:00:00 GMT+0000 (UTC)
## Libraries - p22214-s001_RR-Nkpool - Bead version detected: Enhanced
## References - some-gencodev29.gtf | some-gencodev29.tar.gz | some.fasta
## Parameters - Sample Tag Version: hs | Sample Tag Names:  | VDJ Version: None | Subsample Reads: None | Putative Cell Calling Type: mRNA | Refined Putative Cell Calling: On | Exclude Intronic Reads: Off | Exact Cell Count: None
####################
Cell_Index	Bioproduct	RSEC_Reads	Raw_Molecules	RSEC_Adjusted_Molecules	DBEC_Reads	DBEC_Adjusted_Molecules
2231496	A1BG-AS1	3	1	1	3	1
